name: w2
on:
  workflow_run:
    workflows:
      - 'w1'
    branches: 
      - 'main'
    types:
      - completed      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        check_id: w2
        token: ${{ secrets.GITHUB_TOKEN }}
        conclusion: ${{ job.status }}   
        
