name: Build & Push
on:
  workflow_run:
    workflows:
      - 'tests'
    branches: 
      - 'main'
    types:
      - completed      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        name: Build & Push
        token: ${{ secrets.GITHUB_TOKEN }}
        conclusion: ${{ job.status }}   
        
